version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update rustc
          command: |
            rustup target add wasm32-unknown-unknown
            rustup component add rustfmt
            rustup update
      - run:
           name: Install tools
           command: |
             cargo install chisel
      - run:
           name: Check formatting
           command: |
             rustfmt --version
             cargo fmt -- src/* --check
      - run:
          name: Build
          command: |
             make
             test -f target/wasm32-unknown-unknown/release/sentinel_rs.wasm
