language: rust
rust:
  - nightly
  - stable

script:
  - cargo build --all --release --verbose
  - cargo test --all --verbose
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build --no-default-features; fi
